version = 0.1

[default.global.parameters]
stack_name = "brightedge-crawler"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
fail_on_empty_changeset = false
